#Yaml config file

name: train_CNNSkip_cuda_03
data: ../../data/Giulia_XRF/data2.h5

num_threads: 2
device: cuda

model: CNNSkip
loss: L1Loss
learning_rate: 0.03
batch_size: 256
n_epochs: 100

channels: 32
